### ISSUE TITLE
Support for developer's version

### ISSUE THREAD

**Issue by LostLogia4** [Yukinyaa/KC3Copystuff#1]
directory link is
`mkbfbocigojlcbdjljpnfejpekpkmlae`

**Comment by Yukinyaa** [comment]
mine is [mdejheigapcknbfbegloonaefnajobkp].
I think it changes everytime

**Comment by LostLogia4** [comment]
While you're at it, the application needs to remember the last directory as well.

**Comment by Yukinyaa** [comment]
Not quite what you wanted, but It's working
