### ISSUE TITLE
Which Is Perfered?

### ISSUE THREAD

**Issue by Yukinyaa** [Yukinyaa/KC3Copystuff#6]
``` lang-none
External Saving App
 - Can have trouble on non-window platform
 - Players have to download external program
 - I get a headache
 + which is better then bad headache
 + short dev time
 + fast update
```

``` lang-none
Local app saving feature
 - long dev time
 - slow update
 - I get a bad headache
 + It's local
 + KC3Kai gets new coder
```

let me know what you think

**Comment by LostLogia4** [comment]
Too lazy to do both, I presume?

**Comment by Yukinyaa** [comment]
@LostLogia I could do both, but developing only one should accelerate the project very much

**Comment by ghost** [comment]
The latter for me would be nice imo because apart from myself there are a few other non-windows KC gamers here. Although we don't make up the majority nor am I their representative but to suddenly make a feature windows only seems to already show the bias within the extension.

**Comment by LostLogia4** [comment]
Technically it is possible to port the app into Linux, but this app doesn't seem to be doesn't seem to developed with Linux users in mind.

Anyway, it seems like the local app could benefit more people.
The problem though, is it possible to backup the data periodically with Chrome API alone? :laughing:

**Comment by Yukinyaa** [comment]
@LostLogia4 yes, beleve it is possible.
I am thinking about quickly(in today) finish C# version for prototype and see what feature will be used and what is not.
